version: '3.8'

services:
  csg-server:
    image: madhephaestus/csg-server-app:0.0.4
    container_name: csg-server-app
    volumes:
      # Map your local File.txt to the container
      - "/opt/File.txt:/app/data/File.txt:ro"
    environment:
      # Set virtual display for headless operation
      - DISPLAY=:99
      - QT_X11_NO_MITSHM=1
      - XVFB_WHD=1920x1080x24
    network_mode: host
    restart: unless-stopped
    stdin_open: true
    tty: true
