version: '3.8'

services:
  bowler-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CSG-server
    volumes:
      # Map your local File.txt to the container
      - "/home/hephaestus/File.txt:/app/data/File.txt:ro"
      # X11 forwarding volumes
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    restart: unless-stopped
    stdin_open: true
    tty: true
    # Allow access to X11
    privileged: true
