version: '3.8'

services:
  csg-server:
    image: madhephaestus/csg-server-app:0.0.4
    container_name: csg-server-app
    volumes:
      # Map your local CSG_API.txt to the container
      - "/opt/CSG_API.txt:/app/data/CSG_API.txt:ro"
      # X11 forwarding volumes
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    restart: unless-stopped
    stdin_open: true
    tty: true
    # Allow access to X11
    privileged: true
